name: Type check on PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  type_check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.5.0'
          cache: 'npm'
      - name: Run the type-checker
        shell: bash
        run: npm run type-check
